### ISSUE TITLE
Normalize counts for country performance graphs

### ISSUE THREAD

**Issue by zelima** [cybergreen-net/cg-graphs#22]
Currently unnormalized counts result with graphs that are not much useful for compression as  Total number of counts overweight all the others
![image](https://cloud.githubusercontent.com/assets/15143785/22739069/7bbaa336-ee23-11e6-90dc-4c7e4cff3146.png)

#### normalization

We should plot normalized numbers - i.e. relative to a given baseline e.g. count on 1 Jan 2016 set to 100. If actual count on that date is 50000 we would divide all counts by 500.

QU: what do we do if data is missing on our normalization date?

Example:
```
# actual
country = [
  {date: 2016-01-01, count: 5000}
  {date: 2016-01-02, count: 3000}
  {date: 2016-01-03, count: 7000}
]
global = [
  {date: 2016-01-01, count: 50000}
  {date: 2016-01-02, count: 30000}
  {date: 2016-01-03, count: 80000}
]

# normalized
country = [
  {date: 2016-01-01, count: 100}
  {date: 2016-01-02, count: 60}
  {date: 2016-01-03, count: 140}
]
global = [
  {date: 2016-01-01, count: 100}
  {date: 2016-01-02, count: 60}
  {date: 2016-01-03, count: 160}
]
```

**Comment by rufuspollock** [comment]
I would suggest you assume the incoming data already has a normalized variable e.g.:

```
count: 150000
count_normalized: 125
count_af: 2000000
count_af_normalized: 60000000
```

**Comment by rufuspollock** [comment]
I'm reopening this as it is clear the UX does not work: clear confusion as to what this shows and general sense of "why am I worse than global value -- surely i have less infection than whole world!"

Part of the problem is that set 1 Jan 2017 as 100 for all the series. This means they all artificially converge to that point. But not sure that is the whole answer.

Options (we can do multiple of these):

* Show counts rather than normalized counts
  * And delete global trend for now
  * Could also introduce option to switch between them and start with raw counts ...
* Relabel Global as "Global Trend"
* Change reference time point to mid point -- will make it a bit clearer what is going since you will get convergence point in the middle of the series
* Improve labelling (dubious on this one - people don't see labels)

**Comment by zelima** [comment]
Moved to current milestone

**Comment by zelima** [comment]
No clear decisions here. moving to next milestone
Also removing estimated points as they are set for task that is already done. (was estimated to 8)

**Comment by rufuspollock** [comment]
Plan based on chat today:

* [ ] Remove global trend for now
* [ ] Move to raw counts

**Comment by zelima** [comment]
@rufuspollock are we keeping switching option?

**Comment by zelima** [comment]
FIXED see https://cybergreen-staging.herokuapp.com/country/united-kingdom
